#define GRAD_LANDLINE_DEBUG_MODE true

#define GRAD_LANDLINE_NUMBER_PREFIXES [0030]
#define GRAD_LANDLINE_NUMBER_LENGTH [7,8]

#define GRAD_LANDLINE_CLASSNAMES ["Land_PhoneBooth_01_F", "Land_PhoneBooth_02_F"]