#define GRAD_LANDLINE_NUMBER_PREFIX 030
#define GRAD_LANDLINE_NUMBER_LENGTH [7,8]
#define GRAD_LANDLINE_ALLNUMBERS []

#define GRAD_LANDLINE_CALLS_RUNNING []
#define GRAD_LANDLINE_CLASSNAMES ["Land_PhoneBooth_01_F", "Land_PhoneBooth_02_F"]